### ISSUE TITLE
Segfault when using 17.0.0 and zeromq 4.2.5

### ISSUE THREAD

**Issue by will133** [conda-forge/pyzmq-feedstock#31]
My code seems to segfault after pulling from the latest conda-forge repo (with 17.0.0-py27_4 with zeromq 4.2.5), which I did not get when run with a previous version (17.0.0-py27_3 with zeromq 4.2.3).  It seems like there's some changes in how the pyzmq is built to force the zeromq version to 4.2.5 as well.  Unfortunately it seems like I couldn't get the python stack trace to show so I'm having a hard time narrowing down this.  Do you know if there's any change in build procedures, etc?

```
#0  0x00007f76cabeccd1 in zmq::socket_base_t::process_commands(int, bool) ()
   from /path/lib/python2.7/site-packages/zmq/backend/cython/../../../../../libzmq.so.5
#1  0x00007f76cabed26c in zmq::socket_base_t::getsockopt(int, void*, unsigned long*) ()
   from /path/lib/python2.7/site-packages/zmq/backend/cython/../../../../../libzmq.so.5
#2  0x00007f76cac1176a in zmq::socket_poller_t::check_events(zmq::socket_poller_t::event_t*, int) ()
   from /path/lib/python2.7/site-packages/zmq/backend/cython/../../../../../libzmq.so.5
#3  0x00007f76cac119b9 in zmq::socket_poller_t::wait(zmq::socket_poller_t::event_t*, int, long) ()
   from /path/lib/python2.7/site-packages/zmq/backend/cython/../../../../../libzmq.so.5
#4  0x00007f76cac10225 in zmq_poll ()
   from /path/lib/python2.7/site-packages/zmq/backend/cython/../../../../../libzmq.so.5
#5  0x00007f76c9798b76 in __pyx_pf_3zmq_7backend_6cython_5_poll_zmq_poll.isra.20 ()
   from /path/lib/python2.7/site-packages/zmq/backend/cython/_poll.so
#6  0x00007f76c979ba6e in __pyx_pw_3zmq_7backend_6cython_5_poll_1zmq_poll ()
   from /path/lib/python2.7/site-packages/zmq/backend/cython/_poll.so
#7  0x00007f76d166e7a3 in PyObject_Call () from /path/bin/../lib/libpython2.7.so.1.0
#8  0x00007f76d170256b in PyEval_EvalFrameEx () from /path/bin/../lib/libpython2.7.so.1.0
#9  0x00007f76d170a519 in PyEval_EvalCodeEx () from /path/bin/../lib/libpython2.7.so.1.0
#10 0x00007f76d17074b2 in PyEval_EvalFrameEx () from /path/bin/../lib/libpython2.7.so.1.0
#11 0x00007f76d170a519 in PyEval_EvalCodeEx () from /path/bin/../lib/libpython2.7.so.1.0
#12 0x00007f76d17074b2 in PyEval_EvalFrameEx () from /path/bin/../lib/libpython2.7.so.1.0
#13 0x00007f76d1708ddc in PyEval_EvalFrameEx () from /path/bin/../lib/libpython2.7.so.1.0
#14 0x00007f76d170a519 in PyEval_EvalCodeEx () from /path/bin/../lib/libpython2.7.so.1.0
#15 0x00007f76d169300a in function_call () from /path/bin/../lib/libpython2.7.so.1.0
#16 0x00007f76d166e7a3 in PyObject_Call () from /path/bin/../lib/libpython2.7.so.1.0
#17 0x00007f76d167d53d in instancemethod_call () from /path/bin/../lib/libpython2.7.so.1.0
#18 0x00007f76d166e7a3 in PyObject_Call () from /path/bin/../lib/libpython2.7.so.1.0
#19 0x00007f76d1700708 in PyEval_CallObjectWithKeywords () from /path/bin/../lib/libpython2.7.so.1.0
#20 0x00007f76d1739d76 in t_bootstrap () from /path/bin/../lib/libpython2.7.so.1.0
#21 0x00007f76d1411e25 in start_thread () from /usr/lib64/libpthread.so.0
#22 0x00007f76d0a3634d in clone () from /usr/lib64/libc.so.6

```

**Comment by SylvainCorlay** [comment]
@will133 thanks for reporting. Can you please provide some information about the installed conda packages?

conda list should give us some more information.

**Comment by will133** [comment]
After trying different combinations of this, it seems like the problem has to do with the zeromq 4.2.5-h439df22_0 on anaconda, not conda-forge.  Essentially I tried:

```
Bad:
pyzmq                     17.0.0           py27h14c3975_1    conda/anaconda
zeromq                    4.2.5                h439df22_0    conda/anaconda

Bad:
pyzmq                     17.0.0                   py27_4    conda/conda-forge
zeromq                    4.2.5                h439df22_0    conda/anaconda

Good:
pyzmq                     17.0.0           py27h14c3975_1    conda/anaconda
zeromq                    4.2.5                         1    conda/conda-forge

Good:
zeromq                    4.2.5                         1    conda/conda-forge
pyzmq                     17.0.0                   py27_4    conda/conda-forge
```

Do you know where should I report this btw?

Here is my full environment when I got the segfault:

```
alabaster                 0.7.10           py27he5a193a_0    conda/anaconda
apipkg                    1.4              py27hab8e363_0    conda/anaconda
asn1crypto                0.24.0                   py27_0    conda/anaconda
attrs                     17.4.0                   py27_0    conda/anaconda
babel                     2.5.3                    py27_0    conda/anaconda
bcrypt                    3.1.4            py27h8473b39_0    conda/anaconda
ca-certificates           2018.03.07                    0    conda/anaconda
cairo                     1.14.12              h7636065_2    conda/anaconda
certifi                   2018.1.18                py27_0    conda/anaconda
cffi                      1.11.5           py27h9745a5d_0    conda/anaconda
chardet                   3.0.4            py27hfa10054_1    conda/anaconda
configparser              3.5.0            py27h5117587_0    conda/anaconda
coverage                  4.5.1            py27h14c3975_0    conda/anaconda
cryptography              2.2.2            py27h14c3975_0    conda/anaconda
dnspython                 1.15.0           py27h8b108a9_0    conda/anaconda
docutils                  0.14             py27hae222c1_0    conda/anaconda
enum34                    1.1.6            py27h99a27e9_1    conda/anaconda
execnet                   1.5.0            py27hb11c14a_0    conda/anaconda
expat                     2.2.5                he0dffb1_0    conda/anaconda
flake8                    3.5.0                    py27_1    conda/anaconda
fontconfig                2.12.6               h49f89f6_0    conda/anaconda
freetype                  2.8                  hab7d2ae_1    conda/anaconda
funcsigs                  1.0.2            py27h83f16ab_0    conda/anaconda
gitdb2                    2.0.3                    py27_0    conda/anaconda
gitpython                 2.1.3                    py27_0    conda/anaconda
glib                      2.56.1               h000015b_0    conda/anaconda
graphite2                 1.3.11               hf63cedd_1    conda/anaconda
graphviz                  2.40.1               h25d223c_0    conda/anaconda
harfbuzz                  1.7.6                h5f0a787_1    conda/anaconda
icu                       58.2                 h9c2bf20_1    conda/anaconda
idna                      2.6              py27h5722d68_1    conda/anaconda
imagesize                 1.0.0                    py27_0    conda/anaconda
intel-openmp              2018.0.0                      8    conda/anaconda
ipaddress                 1.0.22                   py27_0    conda/anaconda
jinja2                    2.10             py27h4114e70_0    conda/anaconda
jpeg                      9b                   h024ee3a_2    conda/anaconda
libedit                   3.1                  heed3624_0    conda/anaconda
libffi                    3.2.1                hd88cf55_4    conda/anaconda
libgcc-ng                 7.2.0                hdf63c60_3    conda/anaconda
libgfortran-ng            7.2.0                hdf63c60_3    conda/anaconda
libpng                    1.6.34               hb9fc6fc_0    conda/anaconda
libsodium                 1.0.16               h1bed415_0    conda/anaconda
libstdcxx-ng              7.2.0                hdf63c60_3    conda/anaconda
libtiff                   4.0.9                h28f6b97_0    conda/anaconda
libtool                   2.4.6                h544aabb_3    conda/anaconda
libxcb                    1.13                 h1bed415_1    conda/anaconda
libxml2                   2.9.8                hf84eae3_0    conda/anaconda
lz4                       0.10.1                   py27_0    conda/anaconda
markupsafe                1.0              py27h97b2822_1    conda/anaconda
mccabe                    0.6.1            py27h0e7c7be_1    conda/anaconda
mkl                       2018.0.2                      1    conda/anaconda
mock                      2.0.0            py27h0c0c831_0    conda/anaconda
more-itertools            4.1.0                    py27_0    conda/anaconda
munch                     2.3.1                    py27_0    conda/anaconda
ncurses                   6.0                  h9df7e31_2    conda/anaconda
numpy                     1.11.3           py27h3dfced4_4    conda/anaconda
openssl                   1.0.2o               h20670df_0    conda/anaconda
packaging                 17.1                     py27_0    conda/anaconda
pango                     1.41.0               hd475d92_0    conda/anaconda
paramiko                  2.4.0            py27hc00b698_0    conda/anaconda
pbr                       4.0.2                    py27_0    conda/anaconda
pcre                      8.42                 h439df22_0    conda/anaconda
pip                       9.0.3                    py27_0    conda/anaconda
pixman                    0.34.0               hceecf20_3    conda/anaconda
pluggy                    0.6.0            py27h1f4f128_0    conda/anaconda
py                        1.5.3                    py27_0    conda/anaconda
pyasn1                    0.4.2            py27h1564b0d_0    conda/anaconda
pycodestyle               2.3.1            py27h904819d_0    conda/anaconda
pycparser                 2.18             py27hefa08c5_1    conda/anaconda
pyflakes                  1.6.0            py27h904a57d_0    conda/anaconda
pygments                  2.2.0            py27h4a8b6f5_0    conda/anaconda
pymysql                   0.8.0                    py27_0    conda/anaconda
pynacl                    1.2.1            py27h14c3975_0    conda/anaconda
pyopenssl                 17.5.0           py27hcee3be0_0    conda/anaconda
pyparsing                 2.2.0            py27hf1513f8_1    conda/anaconda
pysocks                   1.6.8                    py27_0    conda/anaconda
pytest                    3.5.0                    py27_0    conda/anaconda
pytest-cov                2.5.1            py27hc4181bb_0    conda/anaconda
pytest-flake8             1.0.0                    py27_0    conda/conda-forge
pytest-forked             0.2              py27h9339617_0    conda/anaconda
pytest-runner             4.2                      py27_0    conda/anaconda
pytest-timeout            1.2.1            py27h0aba353_0    conda/anaconda
pytest-xdist              1.22.2                   py27_0    conda/anaconda
python                    2.7.14              h1571d57_31    conda/anaconda
pytz                      2018.4                   py27_0    conda/anaconda
pyyaml                    3.12             py27h2d70dd7_1    conda/anaconda
pyzmq                     17.0.0           py27h14c3975_1    conda/anaconda
readline                  7.0                  ha6073c6_4    conda/anaconda
requests                  2.18.4           py27hc5b0589_1    conda/anaconda
setuptools                39.0.1                   py27_0    conda/anaconda
six                       1.11.0           py27h5f960f1_1    conda/anaconda
smmap2                    2.0.3                    py27_0    conda/anaconda
snowballstemmer           1.2.1            py27h44e2768_0    conda/anaconda
sphinx                    1.7.2                    py27_0    conda/anaconda
sphinxcontrib             1.0              py27h1512b58_1    conda/anaconda
sphinxcontrib-websupport  1.0.1            py27hf906f22_1    conda/anaconda
sqlite                    3.22.0               h1bed415_0    conda/anaconda
tk                        8.6.7                hc745277_3    conda/anaconda
typing                    3.6.4                    py27_0    conda/anaconda
urllib3                   1.22             py27ha55213b_0    conda/anaconda
wheel                     0.31.0                   py27_0    conda/anaconda
xz                        5.2.3                h55aa19d_2    conda/anaconda
yaml                      0.1.7                had09818_2    conda/anaconda
zeromq                    4.2.5                h439df22_0    conda/anaconda
zlib                      1.2.11               ha838bed_2    conda/anaconda
```

**Comment by jakirkham** [comment]
Please report on [this issue tracker]( https://github.com/AnacondaRecipes/pyzmq-feedstock/issues ).

**Comment by msarahan** [comment]
Cc @mingwandroid

**Comment by mingwandroid** [comment]
Can you share your code @will133?
