### ISSUE TITLE
import error with pyzmq 19.0.2

### ISSUE THREAD

**Issue by HerculesJack** [conda-forge/pyzmq-feedstock#55]
Issue:

Hi, I found that the conda-forge pyzmq 19.0.2 gives the following issue, while downgrading to pyzmq=19.0.1 solves the issue.

```
Python 3.6.11 | packaged by conda-forge | (default, Aug  5 2020, 20:04:48) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import zmq
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/gpfs/share/home/1600011339/.conda/envs/hejia@pku/lib/python3.6/site-packages/zmq/__init__.py", line 50, in <module>
    from zmq import backend
  File "/gpfs/share/home/1600011339/.conda/envs/hejia@pku/lib/python3.6/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/gpfs/share/home/1600011339/.conda/envs/hejia@pku/lib/python3.6/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/gpfs/share/home/1600011339/.conda/envs/hejia@pku/lib/python3.6/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/gpfs/share/home/1600011339/.conda/envs/hejia@pku/lib/python3.6/site-packages/zmq/backend/select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/gpfs/share/home/1600011339/.conda/envs/hejia@pku/lib/python3.6/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: cannot import name 'constants'

```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /gpfs/share/home/1600011339/.conda/envs/hejia@pku:
#
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
argon2-cffi               20.1.0           py36h97a6639_1    conda-forge
attrs                     20.1.0             pyh9f0ad1d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
bleach                    3.1.5              pyh9f0ad1d_0    conda-forge
brotlipy                  0.7.0           py36h97a6639_1000    conda-forge
bzip2                     1.0.8                h516909a_3    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py36hc560c46_0    conda-forge
cffi                      1.14.0           py36hd463f26_0    conda-forge
chardet                   3.0.4           py36hc560c46_1006    conda-forge
cryptography              3.1              py36h8bdcdef_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
entrypoints               0.3             py36hc560c46_1001    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
freetype                  2.10.2               he06d7ca_0    conda-forge
gdbm                      1.18                 h0a1914f_2    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
importlib-metadata        1.7.0            py36hc560c46_0    conda-forge
importlib_metadata        1.7.0                         0    conda-forge
ipykernel                 5.3.4            py36h0b673f9_0    conda-forge
ipython                   7.16.1           py36h0b673f9_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.17.2           py36hc560c46_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
jpeg                      9d                   h516909a_0    conda-forge
json5                     0.9.4              pyh9f0ad1d_0    conda-forge
jsonschema                3.2.0            py36hc560c46_1    conda-forge
jupyter_client            6.1.7                      py_0    conda-forge
jupyter_core              4.6.3            py36hc560c46_1    conda-forge
jupyterlab                2.1.5                      py_0    conda-forge
jupyterlab_server         1.2.0                      py_0    conda-forge
kiwisolver                1.2.0            py36h499bf3f_0    conda-forge
lcms2                     2.11                 hbd6801e_0    conda-forge
ld_impl_linux-64          2.34                 hc38a660_9    conda-forge
libblas                   3.8.0                    16_mkl    conda-forge
libcblas                  3.8.0                    16_mkl    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.3.0               h24d8f2e_16    conda-forge
libgfortran-ng            7.5.0               hdf63c60_16    conda-forge
liblapack                 3.8.0                    16_mkl    conda-forge
libpng                    1.6.37               hed695b0_2    conda-forge
libsodium                 1.0.18               h516909a_0    conda-forge
libstdcxx-ng              9.3.0               hdf63c60_16    conda-forge
libtiff                   4.1.0                hc7e4089_6    conda-forge
libwebp-base              1.1.0                h516909a_3    conda-forge
llvm-openmp               10.0.1               hc9558a2_0    conda-forge
lz4-c                     1.9.2                he1b5a44_3    conda-forge
markupsafe                1.1.1            py36h97a6639_1    conda-forge
matplotlib                3.3.1                         1    conda-forge
matplotlib-base           3.3.1            py36h2451756_1    conda-forge
mistune                   0.8.4           py36h97a6639_1001    conda-forge
mkl                       2020.2                      256    conda-forge
nbconvert                 5.6.1            py36hc560c46_1    conda-forge
nbformat                  5.0.7                      py_0    conda-forge
ncurses                   6.2                  he1b5a44_1    conda-forge
notebook                  6.1.3            py36hc560c46_0    conda-forge
numpy                     1.19.1           py36he0f5f23_2    conda-forge
olefile                   0.46                       py_0    conda-forge
openssl                   1.1.1g               h516909a_1    conda-forge
packaging                 20.4               pyh9f0ad1d_0    conda-forge
pandoc                    2.10.1               h516909a_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.7.1              pyh9f0ad1d_0    conda-forge
pexpect                   4.8.0            py36hc560c46_1    conda-forge
pickleshare               0.7.5           py36hc560c46_1001    conda-forge
pillow                    7.2.0            py36hfc7c323_1    conda-forge
pip                       20.2.2                     py_0    conda-forge
prometheus_client         0.8.0              pyh9f0ad1d_0    conda-forge
prompt-toolkit            3.0.6                      py_0    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
py                        1.9.0              pyh9f0ad1d_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.6.1                      py_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pypy3.6                   7.3.1                h3e02ecb_1    conda-forge
pyrsistent                0.16.0           py36h97a6639_0    conda-forge
pysocks                   1.7.1            py36hc560c46_1    conda-forge
python                    3.6.11          h6f2ec95_2_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.6               1_pypy36_pp73    conda-forge
pyzmq                     19.0.2           py36h058f2d3_0    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
requests                  2.24.0             pyh9f0ad1d_0    conda-forge
scipy                     1.5.2            py36h832618f_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                49.6.0           py36hc560c46_0    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.33.0               h4cf870e_0    conda-forge
terminado                 0.8.3            py36hc560c46_1    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
tornado                   6.0.4            py36h97a6639_1    conda-forge
traitlets                 4.3.3            py36hc560c46_1    conda-forge
urllib3                   1.25.10                    py_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zeromq                    4.3.2                he1b5a44_3    conda-forge
zipp                      3.1.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1007    conda-forge
zstd                      1.4.5                h6597ccf_2    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
Current conda install:

               platform : linux-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.14.2
       root environment : /gpfs/share/software/anaconda/2-4.4.0/pytorch-0.3.1  (read only)
    default environment : /gpfs/share/home/1600011339/.conda/envs/hejia@pku
       envs directories : /gpfs/share/home/1600011339/.conda/envs
                          /gpfs/share/software/anaconda/2-4.4.0/pytorch-0.3.1/envs
          package cache : /gpfs/share/software/anaconda/2-4.4.0/pytorch-0.3.1/pkgs
                          /gpfs/share/home/1600011339/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.14.2 CPython/2.7.13 Linux/3.10.0-514.el7.x86_64 Red Hat Enterprise Linux Server/7.3 glibc/2.17    
                UID:GID : 67188:67456

```
</details>

**Comment by minrk** [comment]
Something's amiss in the environment, because this env appears to *intend* to have pypy (it has pypy3.6), but the Python package is a `cpython` build (`h6f2ec95_2_cpython`). The pyzmq build is the one that assumes pypy, not cpython. When I try to install these two packages in the same env, conda fails with an incompatibility (as it should, they are incompatible):

```
$ conda create -n testenv -c conda-forge python=3.6.11=h6f2ec95_2_cpython pyzmq=19.0.2=py36h058f2d3_0
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
pyzmq==19.0.2=py36h058f2d3_0 -> python[version='>=3.6,<3.7.0a0']
pyzmq==19.0.2=py36h058f2d3_0 -> py -> python[version='2.7.*|3.5.*|3.6.*|3.4.*|>=2.7,<2.8.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0']
python==3.6.11=h6f2ec95_2_cpython
```

I'm not sure how it got into this state, but if you can, I'd delete and recreate the env. If you don't mean to be using pypy, you can also try `conda install python=3.6.*=*cpython` to force a CPython install of Python, which may fix your env (I'm not sure).

I'd also recommend upgrading conda if you can, since you are on 4.3.21 and current is 4.8.

**Comment by HerculesJack** [comment]
@minrk Thanks for the information! On my side it's OK to just use pyzmq=19.0.1 at the moment, although I think it'd be better if conda-forge can fix this at some point.

**Comment by minrk** [comment]
I'm not sure if there is anything for conda-forge to fix, because according to conda, the env you have is rightly considered invalid (current conda will refuse to create an env with the version of Python you have and the version of pyzmq you have because they cannot be used together). I suspect it is a bug in conda that resulted in installing an invalid environment, not something related to conda-forge. There is a very good chance this bug has been fixed in a more recent conda, since the version you have (4.3.21) is at least three years out of date, which is why I suggested upgrading conda, if possible.

**Comment by HerculesJack** [comment]
OK, I see your point now. It might not be easy for me to update conda, however, since I'm using it on a cluster where I don't have root privilege. Nevertheless, I'll close this issue as it's not the fault of conda-forge.

**Comment by minrk** [comment]
Yeah, that is tricky. The first thing I'd do is try to create a new, fresh env and see if it does it again. If you can easily produce an inconsistent env, you might be able to bring that as a stronger case for your cluster admins to upgrade conda. A user install of [miniconda](https://docs.conda.io/en/latest/miniconda.html) might also be worthwhile so you aren't beholden to cluster upgrades.
